---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-sentinel-instance-3
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/sentinel3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-sentinel-instance-3
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: pv-redis-sentinel-instance-3
  resources:
    requests:
      storage: 0.3Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment-redis-sentinel-instance-3
  name: svc-redis-sentinel-instance-3
spec:
  ports:
    - port: 26379
      protocol: TCP
      targetPort: 26379
  selector:
    app: deployment-redis-sentinel-instance-3
  type: LoadBalancer
---