---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-sentinel-instance-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /data/sentinel1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-sentinel-instance-1
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce 
  volumeName: pv-redis-sentinel-instance-1
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment-redis-sentinel-instance-1
  name: svc-redis-sentinel-instance-1
spec:
  ports:
  - port: 26379
    protocol: TCP
    targetPort: 26379
  selector:
    app: deployment-redis-sentinel-instance-1
  type: LoadBalancer
---

