---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-instance-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/redis-instance-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-instance-1
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: pv-redis-instance-1
  resources:
    requests:
      storage: 0.3Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deployment-redis-instance-1
  name: svc-redis-instance-1
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: deployment-redis-instance-1
  type: LoadBalancer
---
